app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, lm
from flask.ext.login import UserMixin


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(16), index=True, unique=True)
    password_hash = db.Column(db.String(64))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def register(username, password):
        user = User(username=username)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()

    def __repr__(self):
        return '<User {0}>'.format(self.username)


@lm.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Length


class LoginForm(Form):
    username = StringField('Username', validators=[Required(), Length(1, 16)])
    password = PasswordField('Password', validators=[Required()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Submit')

app/__init__.py
import os
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager

bootstrap = Bootstrap()
db = SQLAlchemy()
lm = LoginManager()
lm.login_view = 'main.login'


def create_app(config_name):
    """Create an application instance"""
    app = Flask(__name__)

    # import configuration
    cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
    app.config.from_pyfile(cfg)

    # initialize extensions
    bootstrap.init_app(app)
    db.init_app(app)
    lm.init_app(app)

    # import blueprints
    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
from flask import render_template, redirect, url_for, request
from flask.ext.login import login_required, login_user, logout_user
from ..models import User
from . import main
from .forms import LoginForm


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not user.verify_password(form.password.data):
            return redirect(url_for('main.login', **request.args))
        login_user(user, form.remember_me.data)
        return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('login.html', form=form)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@main.route('/')
def index():
    return render_template('index.html')


@main.route('/protected')
@login_required
def protected():
    return render_template('protected.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login Example{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                Login Example
            </a>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('main.protected') }}">Protected</a>
                </li>
            </ul>
            >
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% if current_user.is_authenticated() %}
                        <a href="{{ url_for('main.logout') }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('main.login') }}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/form.html
{% extends "bootstrap/base.html" %}

{%  block title %}Form Example{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('index') }}">Hello</a>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST" action="">
            What is your name? <input type="text" name="name">
            <input type="submit" name="submit" value="Submit">
        </form>
        {%  if name %}
            <h1>Hello, {{ name }}!</h1>
        {% endif %}
    </div>
{% endblock %}

app/templates/form2.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Form Example{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('index') }}">Hello</a>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {{ wtf.quick_form(form) }}
                {% if name %}
                    <h1>Hello, {{ name }}</h1>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
	<h1>Home page</h1>
	<p>This page can be viewed by all users.</p>
	<p>You are {% if not current_user.is_authenticated() %}not {% endif %}
		logged in.</p>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Login</h1>
    <div class="row">
        <div class="col-md-3">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
    <p>This page can be viewed by all users.</p>
    <p>You are {% if not current_user.is_authenticated() %} not {% endif %}
        logged in.</p>
{% endblock %}

app/templates/macros.html
{% macro weather_cell(value,hl) %}
    <td{% if hl %} class="warning"{% endif %}>{{ value }}</td>
{% endmacro %}

{% macro weather_row(month, min, max, rain, hl_min, hl_max, hl_rain) %}
    <tr>
        <td>{{ month }}</td>
        {{ weather_cell(min, min <= hl_min) }}
        {{ weather_cell(max,max >= hl_max) }}
        {{ weather_cell(rain,rain >= hl_rain) }}
    </tr>
{% endmacro %}

app/templates/other.html
<h1>Other Page</h1>
<p>You have a total of {{ count }} page views in this site, the last of which
    was at {{ when }}.</p>
<p><a href="{{ url_for('index5') }}">Click here</a>to see the session page
    .</p>

app/templates/protected.html
{% extends "base.html" %}
{% block title %}Login Example{% endblock %}

{% block page_content %}
    <h1>Protected page</h1>
    <p>This page can only be viewed by logged in users</p>
    <p>You are logged in as <b>{{ current_user.username }}</b></p>
{% endblock %}

app/templates/session.html
<h1>Index Page</h1>
<p>You have a total of {{ count }} page views in this site, the last of which
    was at {{ when }}.</p>
<p><a href="{{ url_for('index6') }}">Click here</a> to see the other page.</p>

app/templates/sqla.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Relational Database Example{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('sqla') }}">Hello</a>
        </div>
    </nav>

{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
        {% if name %}
            <h1>Hello, {{ name }}!</h1>
            {% if new %}
                <p>Pleased to meet you!</p>
            {% else %}
                <p>Happy to see you again!</p>
            {% endif %}
        {% endif %}
    </div>

{% endblock %}

app/templates/upload.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}File Upload Example{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('index') }}">Upload</a>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                {{ wtf.quick_form(form, enctype='multipart/form-data') }}
            </div>
        </div>
        {% if image %}
            <img src="{{ url_for('static', filename=image) }}">
        {% endif %}
    </div>
{% endblock %}

app/templates/user.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <h1>Hello, {{ name }}</h1>
</body>
</html>

app/templates/weather-average.html
{% extends 'base.html' %}
{% import 'macros.html' as macros %}

{% block title %}Weather Averages for {{ city }}{% endblock %}

{% block page_content %}
    <div class="container">
        <h1>Weather Average</h1>

        <h2>{{ city }}</h2>
        <table class="table table-bordered">
            <tr>
                <th>Month</th>
                <th>Min</th>
                <th>Max</th>
                <th>Rainfall</th>
            </tr>
            {% for month in months %}
                {{ macros.weather_row(month,
                weather[month]['min'],
                weather[month]['max'],
                weather[month]['rain'],
                highlight['min'],
                highlight['max'],
                highlight['rain']) }}
            {% endfor %}
        </table>
    </div>
{% endblock %}